apiVersion: v1
kind: Service
metadata:
  name: employee-ui-service
  namespace: employee
spec:
  selector:
    app: employee-ui
  type:  NodePort
  ports:
  - name: http
    protocol: TCP
    port: 4200
    targetPort: 4200