apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-ui-ingress
  namespace: employee
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - employee-ui.sothy.site
    secretName: tls-sothy-site
  rules:
  - host: employee-ui.sothy.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: employee-ui-service
            port: 
              number: 4200