apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-api-ingress
  namespace: employee
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt-production
  #   kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - employee-api.sothy.site
    secretName: tls-sothy-site
  rules:
  - host: employee-api.sothy.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: employee-api-service
            port: 
              number: 4000