apiVersion: v1
kind: Service
metadata:
  name: employee-api-service
  namespace: employee
spec:
  type: ClusterIP
  selector:
    app: employee-api
  ports:
  - port: 4000 # port of service
    targetPort: 4000 # port of pods/container
