apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmate-ingress
  namespace: taskmate
spec:
  ingressClassName: nginx
  rules:
  - host: demo-taskmate.sothy.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: taskmate-service
            port: 
              number: 8000
