apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmate-ingress
  namespace: taskmate
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt-production
  #   kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - demo-taskmate.sothy.site
    secretName: tls-sothy-site
  ingressClassName: nginx
  rules:
  - host: demo-taskmate.sothy.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: taskmate-service
            port: 
              number: 8000
