apiVersion: v1
kind: Service
metadata:
  name: taskmate-service
  namespace: taskmate
spec:
  type: NodePort
  selector:
    app: taskmate
  ports:
  - port: 8000 # port of service
    targetPort: 8000 # port of container
